@startuml DB
hide methods
left to right direction

entity User {
    + id : int <<generated>>
    --
    * email : string(64) <<unique>>
    * username : string(64)
    password : string(64)
    activecampaign_id : int <<FK>>
}

entity Token {
    + value : string(256)
    --
    * user_id : int <<FK>>
    * created_at : Datetime
}

entity Campaign {
    + id : int <<generated>>
    --
    * name : string(64)
    * privacy : boolean
}

entity CampaignUser {
    + campaign_id : int <<FK>>
    + user_id : int <<FK>>
    --
    * role : Role
}

enum Role {
    Owner
    Admin
    Player
}

entity Character {
    + id : int <<generated>>
    --
    * name : string(64)
    * user_id : int <<FK>>
    * campaign_id : int <<FK>>
}

entity Item {
    + id : int <<generated>>
    --
    * name : string(64)
    * campaign_id : int <<FK>>
    owner_id : int <<FK>>
    * slot : string(32)
    * description : string(256)
}

entity CharacterStat {
    + owner_id : int <<FK>>
    + stat_id : int <<FK>>
    --
    * value : int
}

entity Rule {
    + id : int <<generated>>
    --
    name : string(64)
    description : string(1024)
}

entity Stat {
    + id : int <<generated>>
    --
    * rule_id : int <<FK>>
    * name : string(64)
}

entity Tag {
    + id : int <<generated>>
    --
    * name : string(64)
}

entity RuleTag {
    + rule_id : int <<FK>>
    + tag_id : int <<FK>>
}

entity CampaignRule {
    + campaign_id : int <<FK>>
    + rule_id : int <<FK>>
}

entity ItemStat {
    + item_id : int <<FK>>
    + stat_id : int <<FK>>
    --
    slot : string(32)
    * value : int
}

User ||--o{ Token
Campaign ||--o{ Character
Character }o--|| User
Campaign ||--o{ CampaignUser
User ||--o{ CampaignUser
Item }o--o| Character
CharacterStat }o--|| Character
CampaignRule }o--|| Campaign
Rule ||--o{ CampaignRule
CampaignUser -- Role
Campaign ||--o{ Item
Rule ||--o{ Stat
Stat ||--o{ CharacterStat
Rule ||--o{ RuleTag
RuleTag }o--|| Tag
Campaign ||--o{ User
Stat ||--o{ ItemStat
ItemStat }o--|| Item

@enduml